spring.application.name=cbms
spring.main.banner-mode=off
server.port=8080

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Banco de Dados em Memória
spring.datasource.url=jdbc:h2:file:./DB/testdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false