spring.application.name=cbms
spring.main.banner-mode=off
spring.config.import=optional:file:.env[.properties]

server.port=10000
# Sessão - Usar apenas cookies (sem URL rewriting)
server.servlet.session.tracking-modes=COOKIE

# Configurações do Banco de Dados MongoDB
spring.mongodb.uri=${DB_URI}
