name: Java CI/CD and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para criar a release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.vars.outputs.sha_short }}
          name: Release ${{ steps.vars.outputs.sha_short }}
          body: "Release automática do commit ${{ github.sha }}"
          files: target/*.jar
